export const blobs = [
  {
    name: "Color Fusion",
    background: "#9D73F7",
    config: {
      uPositionFrequency: 1,
      uPositionStrength: 0.3,
      uSmallWavePositionFrequency: 0.5,
      uSmallWavePositionStrength: 0.7,
      roughness: 0.5,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.1,
      clearcoatRoughness: 0.2,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "cosmic-fusion",
    },
  },
  {
    name: "Purple Mirror",
    background: "#5300B1",
    config: {
      uPositionFrequency: 0.584,
      uPositionStrength: 0.276,
      uSmallWavePositionFrequency: 0.899,
      uSmallWavePositionStrength: 1.266,
      roughness: 0.3,
      metalness: 0.15,
      envMapIntensity: 0.92,
      clearcoat: 0.3,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "purple-rain",
    },
  },
  {
    name: "Alien Goo",
    background: "#45ACD8",
    config: {
      uPositionFrequency: 1.022,
      uPositionStrength: 0.99,
      uSmallWavePositionFrequency: 0.378,
      uSmallWavePositionStrength: 0.341,
      roughness: 0.35,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.4,
      clearcoatRoughness: 0.3,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "lucky-day",
    },
  },
  {
    name: "Retro CD",
    background: "#1E1E2E",
    config: {
      uPositionFrequency: 0.8,
      uPositionStrength: 0.45,
      uSmallWavePositionFrequency: 1.2,
      uSmallWavePositionStrength: 0.5,
      roughness: 0.25,
      metalness: 0.2,
      envMapIntensity: 0.99,
      clearcoat: 0.5,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "cd",
    },
  },
  {
    name: "Deep Ocean",
    background: "#0D1B2A",
    config: {
      uPositionFrequency: 0.45,
      uPositionStrength: 0.6,
      uSmallWavePositionFrequency: 0.7,
      uSmallWavePositionStrength: 0.8,
      roughness: 0.3,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.4,
      clearcoatRoughness: 0.2,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "deep-ocean",
    },
  },
  {
    name: "Silver Foil",
    background: "#2B2D42",
    config: {
      uPositionFrequency: 1.3,
      uPositionStrength: 0.55,
      uSmallWavePositionFrequency: 1.5,
      uSmallWavePositionStrength: 0.9,
      roughness: 0.35,
      metalness: 0.25,
      envMapIntensity: 0.99,
      clearcoat: 0.3,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "foil",
    },
  },
  {
    name: "Spooky Glow",
    background: "#E65100",
    config: {
      uPositionFrequency: 0.95,
      uPositionStrength: 0.7,
      uSmallWavePositionFrequency: 0.6,
      uSmallWavePositionStrength: 0.4,
      roughness: 0.4,
      metalness: 0.05,
      envMapIntensity: 0.92,
      clearcoat: 0.2,
      clearcoatRoughness: 0.3,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "halloween",
    },
  },
  {
    name: "Cyber Hologram",
    background: "#1A0033",
    config: {
      uPositionFrequency: 1.1,
      uPositionStrength: 0.35,
      uSmallWavePositionFrequency: 1.8,
      uSmallWavePositionStrength: 1.0,
      roughness: 0.25,
      metalness: 0.15,
      envMapIntensity: 0.99,
      clearcoat: 0.5,
      clearcoatRoughness: 0.05,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "hologram",
    },
  },
  {
    name: "Dreamscape",
    background: "#5F27CD",
    config: {
      uPositionFrequency: 0.7,
      uPositionStrength: 0.5,
      uSmallWavePositionFrequency: 0.9,
      uSmallWavePositionStrength: 0.65,
      roughness: 0.35,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.3,
      clearcoatRoughness: 0.2,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "imaginarium",
    },
  },
  {
    name: "Iridescent Pearl",
    background: "#F368E0",
    config: {
      uPositionFrequency: 0.65,
      uPositionStrength: 0.4,
      uSmallWavePositionFrequency: 1.1,
      uSmallWavePositionStrength: 0.75,
      roughness: 0.25,
      metalness: 0.15,
      envMapIntensity: 0.99,
      clearcoat: 0.6,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "iridescent",
    },
  },
  {
    name: "Crimson Passion",
    background: "#900C3F",
    config: {
      uPositionFrequency: 0.85,
      uPositionStrength: 0.5,
      uSmallWavePositionFrequency: 0.5,
      uSmallWavePositionStrength: 0.8,
      roughness: 0.3,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.4,
      clearcoatRoughness: 0.2,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "passion",
    },
  },
  {
    name: "Prism Spectrum",
    background: "#1C1A27",
    config: {
      uPositionFrequency: 1.2,
      uPositionStrength: 0.4,
      uSmallWavePositionFrequency: 1.4,
      uSmallWavePositionStrength: 0.6,
      roughness: 0.3,
      metalness: 0.15,
      envMapIntensity: 0.99,
      clearcoat: 0.5,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "pink-floyd",
    },
  },
  {
    name: "Rainbow Flow",
    background: "#00B894",
    config: {
      uPositionFrequency: 0.75,
      uPositionStrength: 0.55,
      uSmallWavePositionFrequency: 1.0,
      uSmallWavePositionStrength: 0.85,
      roughness: 0.3,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.4,
      clearcoatRoughness: 0.15,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "rainbow",
    },
  },
  {
    name: "Siren Waves",
    background: "#006266",
    config: {
      uPositionFrequency: 0.5,
      uPositionStrength: 0.65,
      uSmallWavePositionFrequency: 0.8,
      uSmallWavePositionStrength: 0.9,
      roughness: 0.35,
      metalness: 0.1,
      envMapIntensity: 0.92,
      clearcoat: 0.4,
      clearcoatRoughness: 0.25,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "sirens",
    },
  },
  {
    name: "Sunset Vibes",
    background: "#FF6B6B",
    config: {
      uPositionFrequency: 0.9,
      uPositionStrength: 0.4,
      uSmallWavePositionFrequency: 0.7,
      uSmallWavePositionStrength: 0.5,
      roughness: 0.4,
      metalness: 0.05,
      envMapIntensity: 0.92,
      clearcoat: 0.3,
      clearcoatRoughness: 0.3,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "sunset-vibes",
    },
  },
  {
    name: "Synthwave Grid",
    background: "#B53471",
    config: {
      uPositionFrequency: 1.15,
      uPositionStrength: 0.48,
      uSmallWavePositionFrequency: 1.3,
      uSmallWavePositionStrength: 0.75,
      roughness: 0.25,
      metalness: 0.15,
      envMapIntensity: 0.99,
      clearcoat: 0.5,
      clearcoatRoughness: 0.1,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "synthwave",
    },
  },
  {
    name: "Snow Pearl",
    background: "#353B48",
    config: {
      uPositionFrequency: 0.6,
      uPositionStrength: 0.35,
      uSmallWavePositionFrequency: 0.6,
      uSmallWavePositionStrength: 0.4,
      roughness: 0.2,
      metalness: 0.05,
      envMapIntensity: 0.92,
      clearcoat: 0.5,
      clearcoatRoughness: 0.05,
      transmission: 0,
      flatShading: false,
      wireframe: false,
      map: "white",
    },
  },
];
